Repository pimcore/data-importer, pull requests merged in 2022-04, with the labels that each got.

#185 [FEATURE] Addeded option to modify asset filename using preg_match on…
  src/Mapping/Operator/Simple/ImportAsset.php
  src/Resources/public/js/pimcore/configuration/components/mapping/operator/importAsset.js
  src/Resources/translations/admin.en.yml
Labels: Improvement

#192 ImportAsset operator: Possibility to overwrite existing assets
  src/Mapping/Operator/Simple/ImportAsset.php
  src/Resources/public/js/pimcore/configuration/components/mapping/operator/importAsset.js
  src/Resources/translations/admin.en.yml
Labels: Improvement

#195 added tests
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/bin/console
  .github/ci/files/config/config.yaml
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/packages/test/config.yaml
  .github/ci/files/config/routes/test/routes.yaml
  .github/ci/files/config/services.yaml
  .github/ci/files/config/system.yml
  .github/ci/files/extensions.template.php
  .github/ci/files/kernel/Kernel.php
  .github/ci/files/public/.htaccess
  .github/ci/files/public/index_test.php
  .github/ci/files/templates/.gitkeep
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/codeception.yml
  .gitignore
  codeception.dist.yml
  composer.json
  tests/Readme.md
  tests/_bootstrap.php
  tests/_support/Helper/Service.php
  tests/_support/Helper/Unit.php
  tests/_support/UnitTester.php
  tests/_support/_generated/ServiceTesterActions.php
  tests/_support/_generated/UnitTesterActions.php
  tests/bin/docker-compose.yml
  tests/bin/init-tests.sh
  tests/unit.suite.yml
  tests/unit/FactoryOperatorTest.php
  tests/unit/QueueTest.php
Labels: Task

#196 Fix nullable quantityvalue
  src/Mapping/Operator/Factory/QuantityValue.php
  src/Mapping/Operator/Factory/QuantityValueArray.php
  src/Resources/public/js/pimcore/configuration/components/mapping/operator/quantityValue.js
  src/Resources/translations/admin.de.yml
  src/Resources/translations/admin.en.yml
  tests/unit/FactoryOperatorTest.php
Labels: Improvement

#197 [Bug]: Import rows with complex data fail
  src/Processing/ImportProcessingService.php
Labels: Bug
