Repository pimcore/data-importer, pull requests merged in 2022-07, with the labels that each got.

#227 [BUGFIX] Fix messenger queue
  src/Resources/config/pimcore/config.yml
Labels: Bug

#225 [Bug]: Classification Store Batch - input quantity value
  src/Mapping/Operator/Factory/InputQuantityValueArray.php
  tests/unit/FactoryOperatorTest.php
Labels: Bug

#229 [Improvement] Allow assigning Countries data type
  doc/03_Configuration/06_Mapping_Configuration/02_Transformation_Pipeline.md
  src/Mapping/Operator/Factory/AsCountries.php
  src/Mapping/Type/TransformationDataTypeService.php
  src/PimcoreDataImporterBundle.php
  src/Resources/config/services/mapping.yml
  src/Resources/public/js/pimcore/configuration/components/mapping/operator/asCountries.js
  src/Resources/translations/admin.en.yml
  tests/unit/FactoryOperatorTest.php
Labels: Improvement

#230 [Improvement] Allow assigning Color data type
  doc/03_Configuration/06_Mapping_Configuration/02_Transformation_Pipeline.md
  src/Mapping/Operator/Factory/AsColor.php
  src/Mapping/Type/TransformationDataTypeService.php
  src/PimcoreDataImporterBundle.php
  src/Resources/config/services/mapping.yml
  src/Resources/public/js/pimcore/configuration/components/mapping/operator/asColor.js
  src/Resources/translations/admin.en.yml
  tests/unit/FactoryOperatorTest.php
Labels: Improvement

#234 Update pimcore version in codeception matrix
  .github/workflows/codeception.yml
Labels: Task
