Repository pimcore/data-importer, pull requests merged in 2023-02, with the labels that each got.

#302 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
Labels: sync

#300 [Task] Added datahub type to `supported_types` config
  src/PimcoreDataImporterBundle.php
  src/Resources/config/pimcore/config.yml
Labels: Task

#295 Fix: Sort packages
  composer.json
Labels: Improvement

#294 Fix: Order
  src/DependencyInjection/Configuration.php
Labels: Improvement

#301 Enhancement: Expose happy path
  src/EventListener/DataImporterListener.php
Labels: Improvement

#298 [Task]: Keep ApplicationLogger compatibility
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  src/Installer.php
  src/PimcoreDataImporterBundle.php
  src/Resources/public/js/pimcore/configuration/components/logTab.js
Labels: Task

#305 [Task]: Added class_alias to phpstan-bootstrap.php to fix phpstan errors
  phpstan-bootstrap.php
Labels: Task

#304 [Improvement]: Delete empty startup.js
  src/PimcoreDataImporterBundle.php
  src/Resources/public/js/pimcore/startup.js
Labels: Improvement

#306 Adapt system.yml - related to https://github.com/pimcore/pimcore/pull/14276
  .github/ci/files/config/system.yml
Labels: sync

#309 [Task]: Add support to PHP 8.2
  composer.json
Labels: Task
