Repository pimcore/data-importer, pull requests merged in 2023-04, with the labels that each got.

#318 [Task]: remove logger aliases from phpStan
  composer.json
  phpstan-bootstrap.php
Labels: Task

#316 [Improvement] Added `PimcoreBundleAdminSupportInterface` to bundle class
  composer.json
  src/PimcoreDataImporterBundle.php
Labels: Improvement

#317 [Task] Replace `Pimcore\File` methods with Filesystem
  src/Command/DummyDataCommand.php
  src/DataSource/Loader/HttpLoader.php
  src/DataSource/Loader/PushLoader.php
  src/DataSource/Loader/SftpLoader.php
Labels: Task

#327 [Bug] Register dependent bundle fix
  src/DependencyInjection/PimcoreDataImporterExtension.php
  src/PimcoreDataImporterBundle.php
Labels: Bug
