Repository pimcore/data-importer, pull requests merged in 2024-04, with the labels that each got.

#401 Unify CLA check
  .github/workflows/cla.yml
Labels: Improvement

#375 Added support to create variants on object creation
  src/Resolver/Location/FindParentStrategy.php
  src/Resolver/Resolver.php
  src/Resources/public/js/pimcore/configuration/components/resolver/location/findParent.js
  src/Resources/translations/admin.en.yml
Labels: Improvement, Pimcore:Priority

#403 fix explode operator to return an empty array when input is empty
  src/Mapping/Operator/Simple/Explode.php
Labels: Bug

#402 fix permanent lock of sequential command, when an error occurs
  src/Command/SequentialProcessQueueCommand.php
Labels: Bug
