Repository pimcore/data-importer, pull requests merged in 2025-03, with the labels that each got.

#458 loadElementByIdentifier Maps Empty String Lookup to IS NULL
  src/Tool/DataObjectLoader.php
Labels: Pimcore:ToDo

#436 Add ObjectField Operator for extracting fields from Data Objects.
  doc/03_Configuration/06_Mapping_Configuration/02_Transformation_Pipeline.md
  src/Mapping/Operator/Simple/ObjectField.php
  src/PimcoreDataImporterBundle.php
  src/Resources/config/services/mapping.yml
  src/Resources/public/js/pimcore/configuration/components/mapping/operator/objectField.js
  src/Resources/translations/admin.en.yml
Labels: New Feature, Pimcore:ToDo

#459 [Task] Consistently use symfony/mime to get MIME type of assets
  phpstan-baseline.neon
  src/DataSource/Interpreter/CsvFileInterpreter.php
Labels: Task

#460 [Task] Remove BC Layer for DataObject Service (getVersionDependentDatabaseColumnName)
  src/Resolver/Load/IdStrategy.php
  src/Resolver/Load/PathStrategy.php
Labels: Task

#452 Fix file caching in JsonFileInterpreter.
  src/DataSource/Interpreter/JsonFileInterpreter.php
Labels: Bug, Pimcore:ToDo

#438 Fix usage of cache in XmlFileInterpreter
  src/DataSource/Interpreter/XmlFileInterpreter.php
Labels: Bug, Pimcore:ToDo

#465 [Bug] Add int cast to loadById in DataObjectLoader
  src/Tool/DataObjectLoader.php
Labels: Bug
