Repository pimcore/data-importer, pull requests merged in 2025-02, with the labels that each got.

#451 [Task] Support data-hub 2.0 and clean up code
  composer.json
  src/Command/CronExecutionCommand.php
  src/Command/ParallelizationAbstractCommand.php
  src/Controller/ConfigDataObjectController.php
  src/Installer.php
  src/PimcoreDataImporterBundle.php
  src/Preview/PreviewService.php
  src/Settings/ConfigurationPreparationService.php
Labels: Task

#449 Update carbon
  composer.json
Labels: Pimcore:ToDo, Internal

#454 Update workflows to use centralized approach
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
Labels: Task, Pimcore:ToDo

#457 [Task] Add container extension
  src/PimcoreDataImporterBundle.php
Labels: Task, Pimcore:ToDo

#437 Data Selector for JSON Payload
  composer.json
  src/DataSource/Interpreter/JsonFileInterpreter.php
  src/Resources/public/js/pimcore/configuration/components/interpreter/json.js
  src/Resources/translations/admin.en.yml
Labels: Improvement, Pimcore:ToDo
